# Generated by Django 2.1.7 on 2019-06-12 13:21

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+420775966561', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
