# Generated by Django 2.1.7 on 2019-06-16 10:49

import address.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20190616_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='contacts',
            field=models.ManyToManyField(blank=True, null=True, related_name='skills', to='contacts.Contact'),
        ),
    ]
