# Generated by Django 2.1.7 on 2019-06-25 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('name', 'level')},
        ),
    ]
